### ISSUE TITLE
Lacks "Settings" link in Plugin page

### ISSUE THREAD

**Issue by objarni** [einand/visitor-status-for-cilamp#4]
See screenshot.

![image](https://user-images.githubusercontent.com/68198/34453649-e94e71da-ed59-11e7-85dc-3d7b878800be.png)

Expected a "Settings" link beside the Deactivate link, like the other plugins.

**Comment by einand** [comment]
won't happen, there is a good menu for it

**Comment by objarni** [comment]
The menu item/icon is great! This is more about following the pattern of other plugins.

**Comment by einand** [comment]
its up the the other plugins to break the api, I won't.

—
Ein Andersson

> 1 jan. 2018 kl. 18:42 skrev Olof Bjarnason <notifications@github.com>:
> 
> —

**Comment by objarni** [comment]
Is adding a "Settings" link breaking the official wordpress plugins API / guidelines?

**Comment by einand** [comment]
looks like its starting to get official support, but it still says 

This page is marked <https://codex.wordpress.org/Category:Stubs> as incomplete. You can help <https://codex.wordpress.org/Codex:Contributing> Codex by expanding it <http://codex.wordpress.org/index.php?title=Plugin_API/Filter_Reference/plugin_action_links_(plugin_file_name)&action=edit>.

in the documentation 

Anyway its a bad habit and should not be encouraged to have settings link there.

 
—
Ein Andersson

**Comment by objarni** [comment]
As a user of wordpress since something like 10 years back, I would never have guessed the Settings link was not recommended. If anything, to me it's a very easy to find place to look for a plugins settings; so that I don't have to look through the main menu, the settings menu, the tools menu, and even sometimes the customize-page of a theme. Come to think of it, this part of the WP "UX" has always felt a bit 'unpolished'.

But I don't want the plugin to go against an official guideline either. Good spot.
