### ISSUE TITLE
Cumbersom upgrade process

### ISSUE THREAD

**Issue by objarni** [einand/visitor-status-for-cilamp#5]
1. Download zip
2. Deactivate old plugin
3. Delete old plugin (otherwise installation of new fails)
4. Upoad new .zip
5. Install new version
6. Verify version in plugins section.

If the plugin was published on wp.com it would be almost a "one click" process to update.

**Comment by einand** [comment]
this bug should be adressed to wordpress, there are nothing i can do about the update process.

**Comment by objarni** [comment]
The update process is perfectly fine for plugins published to wordpress.com official repository.

So this issue is about publishing the plugin I guess.
