### ISSUE TITLE
"Save" gives no UX feedback

### ISSUE THREAD

**Issue by objarni** [einand/visitor-status-for-cilamp#6]
When hitting "Save" on settings page, I expect some kind of "settings save" ux feedback. This is what happens on e.g. page cache clear in W3 Total Cache plugin, or "Save" in visual composer, see screenshot.

![image](https://user-images.githubusercontent.com/68198/34453716-48e4fdf2-ed5b-11e7-96b0-807aef8db6e1.png)

**Comment by einand** [comment]
Its now fixed in version 0.3.1

**Comment by objarni** [comment]
Nice, will test directly :)

**Comment by objarni** [comment]
The feedback on Save looks right, but when visiting the page I got the attached behaviour, a warning message of some kind?

![image](https://user-images.githubusercontent.com/68198/34469917-a8cd46e8-ef27-11e7-843d-bd24853133b2.png)

**Comment by einand** [comment]
fixed in 0.3.2

Its an old bug from when the plugin required nonce

—
Ein Andersson
